export { default as Navbar } from './Navbar/Navbar';
export { default as Footer } from './Footer/Footer';
export { default as HomeCover } from './HomeCover/Cover';
export { default as Programs } from './Programs/Programs';
export { default as Statistics } from './Statistics/Statistics';
export { default as Community } from './Community/Community';
export { default as Information } from './Information/Information';
export { default as Partner } from './Partner/Partner';
export { default as AboutUsCover } from './AboutUsCover/Cover';